# Generated by Django 6.0.3 on 2026-03-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', '개발자'), ('PRESIDENT', '모임장'), ('ADMIN', '운영진'), ('MEMBER', '일반회원')], default='MEMBER', max_length=20),
        ),
    ]
