# Generated by Django 6.0.3 on 2026-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_taking_lessons',
            field=models.BooleanField(default=False),
        ),
    ]
