# Generated by Django 6.0.3 on 2026-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_taking_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('S', 'S조'), ('A', 'A조'), ('B', 'B조'), ('C', 'C조'), ('D', 'D조'), ('Beginner', '초심')], default='BEGINNER', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
