version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: minton_mysql
    restart: always
    environment:
      MYSQL_DATABASE: minton_db
      MYSQL_USER: minton_user
      MYSQL_PASSWORD: minton_password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: Asia/Seoul
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: