# Generated by Django 6.0.3 on 2026-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_attendance_created_at_alter_attendance_meetup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='meetup_type',
            field=models.CharField(choices=[('REGULAR', '정기운동'), ('LIGHTNING', '번개운동')], default='REGULAR', max_length=20),
        ),
    ]
