# Generated by Django 6.0.3 on 2026-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='guest_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guest_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
